message: "API Gateway Service"

spring:
  servlet:
    multipart:
      max-file-size: 5MB
server:
  port: ${GATEWAY_PORT:8090}
zuul:
  routes:
    user-service:
      path: /user-service/**
      serviceId: UserService
    user-authentication-service:
      path: /user-authentication-service/**
      serviceId: UserAuthenticationService
    inventory-service:
      path: /inventory-service/**
      serviceId: InventoryService
    cart-service:
      path: /cart-service/**
      serviceId: CartService
    order-service:
      path: /order-service/**
      serviceId: OrderService      
                 


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true    


