server:
  port: ${ORDER_SERVICE_PORT:9016}
spring:
  data:
    mongodb:
      database: ${ORDER_DB:e_commerce_db}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true    
  
