jwt:
  secret: ${SECRET_KEY:secret}
server:
  port: ${SERVER_PORT:9004}
spring:
  data:
    mongodb:
      database: ${AUTHENTICATION_DB:e_commerce_db}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true    

